// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpQUL3kQg0MBE8uLF_ThqG5cZ8G9xlRo',
    appId: '1:822680207703:web:b7505346c82e1cf6b07e12',
    messagingSenderId: '822680207703',
    projectId: 'ecom-cool-pj',
    authDomain: 'ecom-cool-pj.firebaseapp.com',
    storageBucket: 'ecom-cool-pj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjYC5T3UJa49lz_u_a-BfvyX58u_JtCs',
    appId: '1:822680207703:android:d020c1d40ff03c90b07e12',
    messagingSenderId: '822680207703',
    projectId: 'ecom-cool-pj',
    storageBucket: 'ecom-cool-pj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QI35aG1ihYowey7vSkWdXtKm_loy9Ro',
    appId: '1:822680207703:ios:d1502289702e666ab07e12',
    messagingSenderId: '822680207703',
    projectId: 'ecom-cool-pj',
    storageBucket: 'ecom-cool-pj.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1QI35aG1ihYowey7vSkWdXtKm_loy9Ro',
    appId: '1:822680207703:ios:d1502289702e666ab07e12',
    messagingSenderId: '822680207703',
    projectId: 'ecom-cool-pj',
    storageBucket: 'ecom-cool-pj.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVpQUL3kQg0MBE8uLF_ThqG5cZ8G9xlRo',
    appId: '1:822680207703:web:88d0d4baa0df8c2eb07e12',
    messagingSenderId: '822680207703',
    projectId: 'ecom-cool-pj',
    authDomain: 'ecom-cool-pj.firebaseapp.com',
    storageBucket: 'ecom-cool-pj.firebasestorage.app',
  );

}